---
abstract: 'bindings for librdkafka'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.94'
configure_requires:
  Alien::Base::Wrapper: '0'
  Alien::Librdkafka: v0.9.3
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.60, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Kafka-Librd
no_index:
  directory:
    - t
    - inc
requires:
  Exporter::Lite: '0'
  Sub::Install: '0'
resources:
  bugtracker: https://github.com/uperl/Kafka-Librd/issues
  homepage: https://metacpan.org/pod/Kafka::Librd
  repository: https://github.com/uperl/Kafka-Librd.git
version: '0.20'
x_contributors:
  - 'Pavel Shaydo <zwon@cpan.org>'
  - 'Graham Ollis <plicease@cpan.org>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
