Name:           perl-Kafka-Librd
Version:        0.14
Release:        1%{?dist}
Summary:        Bindings for librdkafka
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Kafka-Librd/
Source0:        http://www.cpan.org/modules/by-module/Kafka/Kafka-Librd-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(Exporter::Lite)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More) >= 0.94
BuildRequires:  librdkafka-devel >= 0.9.3
Requires:       librdkafka => 0.9.3
Requires:       perl(Exporter::Lite)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module provides perl bindings for librdkafka.

%prep
%setup -q -n Kafka-Librd-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Kafka*
%{_mandir}/man3/*

%changelog
* Sat Mar 14 2020 Michael R. Davis <mdavis@stopllc.com> 0.14-1
- Specfile autogenerated by cpanspec 1.78.
