Name:           perl-Kafka-Librd
Version:        0.15
Release:        1%{?dist}
Summary:        Bindings for librdkafka
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://metacpan.org/release/Kafka-Librd
Source0:        https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Kafka-Librd-%{version}.tar.gz
Patch:          perl-Kafka-Librd-rpm-el7.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(Exporter::Lite)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More) >= 0.94
BuildRequires:  librdkafka-devel >= 0.9.3
Requires:       librdkafka => 0.9.3
Requires:       perl(Exporter::Lite)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module provides perl bindings for librdkafka.

%prep
%setup -q -n Kafka-Librd-%{version}
%patch -p1

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Kafka*
%{_mandir}/man3/*

%changelog
* Sat Apr 04 2020 Michael R. Davis <mrdvt@cpan.org> 0.15-1
- Updated to version 0.15
- Updates for rpmlint

* Sat Apr 03 2020 Michael R. Davis <mrdvt@cpan.org> 0.14-2
- Added Patch capability

* Sat Mar 14 2020 Michael R. Davis <mrdvt@cpan.org> 0.14-1
- Specfile autogenerated by cpanspec 1.78.
